name: Build Java AMI

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Terraform Init
        run: |
          terraform -chdir=terraform init \
            -backend-config="key=ami/java/terraform.tfstate"

      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var="terraform_state_bucket=tfstate-286325277771-eu-west-1"

      - name: Start Image Build
        run: |
          PIPELINE_ARN=$(terraform -chdir=terraform output -raw image_pipeline_arn)

          aws imagebuilder start-image-pipeline-execution \
            --image-pipeline-arn "$PIPELINE_ARN"